//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MvcTable
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Anime { get; set; }
    }
}
